imports:
  - { resource: shared/checkout.yaml }

services:

  sylius.google_tag_manager.enhanced_ecommerce_tracking.add_payment_info:
    parent: sylius.google_tag_manager.enhanced_ecommerce_tracking.checkout_step.abstract
    arguments: [5]
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
