imports:
    - { resource: shared/cart.yaml }

services:
    sylius.google_tag_manager.enhanced_ecommerce_tracking.cart.listener.add_to_cart:
        parent: sylius.google_tag_manager.enhanced_ecommerce_tracking.cart.listener.abstract
        tags:
            - { name: kernel.event_listener, event: sylius.cart_item_add, method: onAddToCart }
            - { name: kernel.event_listener, event: sylius.order_item.post_add, method: onAddToCart }
