imports:
  - { resource: shared/checkout.yaml }

services:

  sylius.google_tag_manager.enhanced_ecommerce_tracking.view_cart:
    parent: sylius.google_tag_manager.enhanced_ecommerce_tracking.checkout_step.abstract
    arguments: [1]
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
