imports:
    - { resource: shared/cart.yaml }

services:
    sylius.google_tag_manager.enhanced_ecommerce_tracking.cart.listener.view_cart:
        parent: sylius.google_tag_manager.enhanced_ecommerce_tracking.cart.listener.abstract
        tags:
            - { name: kernel.event_listener, event: sylius.cart_summary, method: onCartSummary }
            - { name: kernel.event_listener, event: sylius.order.cart_summary, method: onCartSummary }
