services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false

  sylius.google_tag_manager.enhanced_ecommerce_tracking.cart.listener.controller:
    class: StefanDoorn\SyliusGtmEnhancedEcommercePlugin\EventListener\CartListener
    arguments:
      - '@request_stack'
      - '@sylius.google_tag_manager.enhanced_ecommerce_tracking.tag_manager.cart'
      - "@security.firewall.map"
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
