services:
    sylius.google_tag_manager.enhanced_ecommerce_tracking.cart.listener.abstract:
        abstract: true
        class: StefanDoorn\SyliusGtmEnhancedEcommercePlugin\EventListener\CartListener
        arguments:
            - "@sylius.context.cart"
            - "@sylius.google_tag_manager.enhanced_ecommerce_tracking.tag_manager.cart"
