services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false

  sylius.google_tag_manager.enhanced_ecommerce_tracking.purchases.listener.thank_you:
    class: StefanDoorn\SyliusGtmEnhancedEcommercePlugin\EventListener\ThankYouListener
    arguments:
      - "@sylius.google_tag_manager.enhanced_ecommerce_tracking.tag_manager.add_transaction"
      - "@sylius.repository.order"
    tags:
      - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
