name: Build

on:
    push:
        branches-ignore:
            - 'dependabot/**'
        paths-ignore:
            - "*.md"
    pull_request:
        paths-ignore:
            - "*.md"
    release:
        types: [created]
    schedule:
        -
            cron: "0 1 * * 6" # Run at 1am every Saturday
    workflow_dispatch: ~

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    tests:
        runs-on: ubuntu-latest

        name: "Sylius ${{ matrix.sylius }}, PHP ${{ matrix.php }}, Symfony ${{ matrix.symfony }}, MySQL ${{ matrix.mysql }}"

        strategy:
            fail-fast: false
            matrix:
                php: ["8.2", "8.3", "8.4"]
                symfony: ["^6.4", "^7.2"]
                sylius: ["~2.0.0"]
                database: ["mysql:9.0"]
                node: ["20.x"]

        env:
            APP_ENV: test

        steps:
            -   uses: actions/checkout@v4

            -   name: Build Sylius Test Application
                uses: SyliusLabs/BuildTestAppAction@v4
                with:
                    e2e_js: "no"
                    database: "${{ matrix.database }}"
                    node_version: "${{ matrix.node }}"
                    php_version: "${{ matrix.php }}"
                    sylius_version: "${{ matrix.sylius }}"
                    symfony_version: "${{ matrix.symfony }}"

            -   name: Validate composer.json
                run: composer validate --ansi --strict

            -   name: Run security check
                run: composer audit --abandoned=ignore

            -   name: Check coding standard
                run: composer check-style

            -   name: Run PHPStan
                run: composer analyse

            -   name: Run tests
                run: composer test
